# -*- coding: utf-8 -*-
"""compiledMillets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EWm1JORnpu0gIx5aK-fJ-kUBlF78Va2J

# file uploading
"""

!unzip /content/bajra_sorted.zip

!unzip /content/ragi.zip

"""# checking files"""

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

# Paths to your folders
bajra_path = "/content/bajra_sorted"
ragi_path = "/content/ragi"

# Function to recursively get image paths
def get_image_paths_recursive(folder, extensions={'.jpg', '.jpeg', '.png'}):
    paths = []
    for root, dirs, files in os.walk(folder):
        for file in files:
            if os.path.splitext(file)[1].lower() in extensions:
                paths.append(os.path.join(root, file))
    return paths

# Get all image paths
bajra_images = get_image_paths_recursive(bajra_path)
ragi_images = get_image_paths_recursive(ragi_path)

print(f"🔹 Bajra Images: {len(bajra_images)}")
print(f"🔹 Ragi Images: {len(ragi_images)}")

# Analysis function
def analyze_images(image_list, label):
    heights, widths = [], []
    color_means, color_stds = [], []

    for img_path in image_list:
        img = cv2.imread(img_path)
        if img is None:
            continue
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        h, w, _ = img.shape
        heights.append(h)
        widths.append(w)
        mean = img_rgb.mean(axis=(0, 1))
        std = img_rgb.std(axis=(0, 1))
        color_means.append(mean)
        color_stds.append(std)

    print(f"\n📊 Analysis for {label}:")
    if heights:
        print(f" - Avg Height: {np.mean(heights):.2f}")
        print(f" - Avg Width: {np.mean(widths):.2f}")
        print(f" - Avg RGB Mean: {np.mean(color_means, axis=0).astype(int)}")
        print(f" - Avg RGB Std: {np.mean(color_stds, axis=0).astype(int)}")
    else:
        print(" - No valid images found for stats.")

    # Plot sample images
    sample_imgs = image_list[:5]
    plt.figure(figsize=(15, 3))
    for i, img_path in enumerate(sample_imgs):
        img = Image.open(img_path)
        plt.subplot(1, 5, i+1)
        plt.imshow(img)
        plt.axis('off')
        plt.title(f"{label} #{i+1}")
    plt.show()

# Run analysis
analyze_images(bajra_images, "Bajra")
analyze_images(ragi_images, "Ragi")

import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter
from PIL import Image

def get_images_and_labels(root_dir, extensions={'.jpg', '.jpeg', '.png'}):
    image_paths = []
    labels = []
    for root, dirs, files in os.walk(root_dir):
        for file in files:
            if os.path.splitext(file)[1].lower() in extensions:
                image_paths.append(os.path.join(root, file))
                labels.append(os.path.basename(root))  # folder name = label
    return image_paths, labels
bajra_images, bajra_labels = get_images_and_labels("/content/bajra_sorted")
ragi_images, ragi_labels = get_images_and_labels("/content/ragi")
all_images = bajra_images + ragi_images
all_labels = bajra_labels + ragi_labels

widths, heights = [], []
rgb_means = []

for img_path in all_images:
    img = cv2.imread(img_path)
    if img is None:
        continue
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    h, w, _ = img.shape
    widths.append(w)
    heights.append(h)
    rgb_means.append(img_rgb.mean(axis=(0, 1)))  # [R,G,B]

rgb_means = np.array(rgb_means)

plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.hist(widths, bins=20, color='skyblue', edgecolor='black')
plt.title('Image Width Distribution')
plt.xlabel('Width (pixels)')
plt.ylabel('Frequency')

plt.subplot(1,2,2)
plt.hist(heights, bins=20, color='lightgreen', edgecolor='black')
plt.title('Image Height Distribution')
plt.xlabel('Height (pixels)')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(12,4))
plt.hist(rgb_means[:,0], bins=30, color='r', alpha=0.6, label='Red')
plt.hist(rgb_means[:,1], bins=30, color='g', alpha=0.6, label='Green')
plt.hist(rgb_means[:,2], bins=30, color='b', alpha=0.6, label='Blue')
plt.title('Average RGB Channel Distributions')
plt.xlabel('Average Channel Value')
plt.ylabel('Frequency')
plt.legend()
plt.show()

all_class_counts = Counter(bajra_labels) + Counter(ragi_labels)
classes, counts = zip(*all_class_counts.items())

plt.figure(figsize=(10,5))
plt.bar(classes, counts, color='orchid', edgecolor='black')
plt.title('Number of Images per Class')
plt.xlabel('Class')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

"""# work on ragi"""

import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

# ✅ Load dataset
data_dir = '/content/ragi'

# Create training & validation datasets
batch_size = 32
img_height = 180
img_width = 180

train_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="training",
    seed=42,
    image_size=(img_height, img_width),
    batch_size=batch_size
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="validation",
    seed=42,
    image_size=(img_height, img_width),
    batch_size=batch_size
)

class_names = train_ds.class_names
print("Classes:", class_names)

# ✅ Improve performance
AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

# ✅ Build CNN model
model = models.Sequential([
    layers.Rescaling(1./255, input_shape=(img_height, img_width, 3)),

    layers.Conv2D(32, 3, activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(64, 3, activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(128, 3, activation='relu'),
    layers.MaxPooling2D(),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(len(class_names), activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# ✅ Train the model
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20
)

# ✅ Plot training results
plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='train_acc')
plt.plot(history.history['val_accuracy'], label='val_acc')
plt.title('Accuracy over epochs')
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='train_loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.title('Loss over epochs')
plt.legend()

plt.show()

import random
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image

# ✅ Pick a random image path from the dataset
import os
import glob

# Recursively find all images
all_image_paths = glob.glob('/content/ragi/**/*.*', recursive=True)
random_image_path = random.choice(all_image_paths)
print(f"Selected image: {random_image_path}")

# ✅ Load and preprocess image
img = image.load_img(random_image_path, target_size=(img_height, img_width))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)  # shape becomes (1, height, width, 3)
img_array /= 255.0  # same as our Rescaling layer

# ✅ Make prediction
predictions = model.predict(img_array)
predicted_class_idx = np.argmax(predictions[0])
predicted_class_name = class_names[predicted_class_idx]

print(f"🔍 Predicted class: {predicted_class_name}")

# ✅ Show image with prediction
plt.imshow(img)
plt.title(f"Predicted: {predicted_class_name}")
plt.axis('off')
plt.show()

"""cnn + attention now"""

import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

# =====================
# Data loading
# =====================
data_dir = '/content/ragi'
batch_size = 32
img_height = 180
img_width = 180

train_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="training",
    seed=42,
    image_size=(img_height, img_width),
    batch_size=batch_size
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="validation",
    seed=42,
    image_size=(img_height, img_width),
    batch_size=batch_size
)

class_names = train_ds.class_names
print("Classes:", class_names)

AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

# =====================
# CNN + simple spatial attention
# =====================
inputs = layers.Input(shape=(img_height, img_width, 3))
x = layers.Rescaling(1./255)(inputs)

x = layers.Conv2D(32, 3, activation='relu')(x)
x = layers.MaxPooling2D()(x)

x = layers.Conv2D(64, 3, activation='relu')(x)
x = layers.MaxPooling2D()(x)

x = layers.Conv2D(128, 3, activation='relu')(x)
x = layers.MaxPooling2D()(x)

# 🧠 Spatial attention
attention = layers.Conv2D(1, kernel_size=1, activation='sigmoid')(x)
x = layers.multiply([x, attention])  # apply attention mask

x = layers.Flatten()(x)
x = layers.Dense(128, activation='relu')(x)
x = layers.Dropout(0.5)(x)
outputs = layers.Dense(len(class_names), activation='softmax')(x)

model = models.Model(inputs, outputs)

# =====================
# Compile and train
# =====================
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20
)

# =====================
# Plot accuracy & loss
# =====================
plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='train_acc')
plt.plot(history.history['val_accuracy'], label='val_acc')
plt.title('Accuracy over epochs')
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='train_loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.title('Loss over epochs')
plt.legend()
plt.show()

import random
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image
import glob

# ✅ Pick a random image from your dataset
all_image_paths = glob.glob('/content/ragi/**/*.*', recursive=True)
random_image_path = random.choice(all_image_paths)
print(f"Selected image: {random_image_path}")

# ✅ Load and preprocess
img = image.load_img(random_image_path, target_size=(img_height, img_width))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)  # shape (1, H, W, 3)
img_array /= 255.0  # normalize like training

# ✅ Predict
predictions = model.predict(img_array)
predicted_class_idx = np.argmax(predictions[0])
predicted_class_name = class_names[predicted_class_idx]

print(f"🔍 Predicted class: {predicted_class_name}")

# ✅ Display image
plt.imshow(img)
plt.title(f"Predicted: {predicted_class_name}")
plt.axis('off')
plt.show()

"""MobileNetV2"""

import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

# ================
# Load dataset
# ================
data_dir = '/content/ragi'
batch_size = 32
img_height = 180
img_width = 180

train_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="training",
    seed=42,
    image_size=(img_height, img_width),
    batch_size=batch_size
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="validation",
    seed=42,
    image_size=(img_height, img_width),
    batch_size=batch_size
)

class_names = train_ds.class_names
print("Classes:", class_names)

AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

# ================
# MobileNetV2 model
# ================
base_model = tf.keras.applications.MobileNetV2(
    input_shape=(img_height, img_width, 3),
    include_top=False,
    weights='imagenet'
)
base_model.trainable = False  # freeze base

# Build classification head
inputs = layers.Input(shape=(img_height, img_width, 3))
x = tf.keras.applications.mobilenet_v2.preprocess_input(inputs)
x = base_model(x, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dropout(0.3)(x)
outputs = layers.Dense(len(class_names), activation='softmax')(x)

model = models.Model(inputs, outputs)

# Compile
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# ================
# Train for 20 epochs
# ================
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20
)

# ================
# Plot training history
# ================
plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='train_acc')
plt.plot(history.history['val_accuracy'], label='val_acc')
plt.title('Accuracy over epochs')
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='train_loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.title('Loss over epochs')
plt.legend()
plt.show()

import random
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image
import glob

# ✅ Pick random image from dataset
all_image_paths = glob.glob('/content/ragi/**/*.*', recursive=True)
random_image_path = random.choice(all_image_paths)
print(f"Selected image: {random_image_path}")

# ✅ Load and preprocess for MobileNetV2
img = image.load_img(random_image_path, target_size=(img_height, img_width))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)  # shape (1, H, W, 3)
img_array = tf.keras.applications.mobilenet_v2.preprocess_input(img_array)

# ✅ Predict
predictions = model.predict(img_array)
predicted_class_idx = np.argmax(predictions[0])
predicted_class_name = class_names[predicted_class_idx]

print(f"🔍 Predicted class: {predicted_class_name}")

# ✅ Show image with prediction
plt.imshow(image.load_img(random_image_path))
plt.title(f"Predicted: {predicted_class_name}")
plt.axis('off')
plt.show()

"""# work on bajra/pearl millet"""

import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

# ================
# Load bajra dataset
# ================
data_dir = '/content/bajra_sorted'
batch_size = 32
img_height = 180
img_width = 180

train_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="training",
    seed=42,
    image_size=(img_height, img_width),
    batch_size=batch_size
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="validation",
    seed=42,
    image_size=(img_height, img_width),
    batch_size=batch_size
)

class_names = train_ds.class_names
print("Classes:", class_names)

AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

# ================
# Build simple CNN
# ================
model = models.Sequential([
    layers.Rescaling(1./255, input_shape=(img_height, img_width, 3)),
    layers.Conv2D(32, 3, activation='relu'),
    layers.MaxPooling2D(),
    layers.Conv2D(64, 3, activation='relu'),
    layers.MaxPooling2D(),
    layers.Conv2D(128, 3, activation='relu'),
    layers.MaxPooling2D(),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(len(class_names), activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# ================
# Train for 20 epochs
# ================
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20
)

# ================
# Plot training curves
# ================
plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='train_acc')
plt.plot(history.history['val_accuracy'], label='val_acc')
plt.title('Accuracy over epochs')
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='train_loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.title('Loss over epochs')
plt.legend()
plt.show()

import random
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image
import glob

# ✅ Pick random image from bajra dataset
all_image_paths = glob.glob('/content/bajra_sorted/**/*.*', recursive=True)
random_image_path = random.choice(all_image_paths)
print(f"Selected image: {random_image_path}")

# ✅ Load and preprocess
img = image.load_img(random_image_path, target_size=(img_height, img_width))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array /= 255.0

# ✅ Predict
predictions = model.predict(img_array)
predicted_class_idx = np.argmax(predictions[0])
predicted_class_name = class_names[predicted_class_idx]

print(f"🔍 Predicted class: {predicted_class_name}")

# ✅ Display
plt.imshow(image.load_img(random_image_path))
plt.title(f"Predicted: {predicted_class_name}")
plt.axis('off')
plt.show()

"""cnn+ attention"""

import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

# ====================
# Load bajra dataset
# ====================
data_dir = '/content/bajra_sorted'
batch_size = 16
img_height = 128
img_width = 128

train_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="training",
    seed=42,
    image_size=(img_height, img_width),
    batch_size=batch_size
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="validation",
    seed=42,
    image_size=(img_height, img_width),
    batch_size=batch_size
)

class_names = train_ds.class_names
print("Classes:", class_names)

AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

# ====================
# Middle-ground CNN + attention
# ====================
inputs = layers.Input(shape=(img_height, img_width, 3))
x = layers.Rescaling(1./255)(inputs)

x = layers.Conv2D(64, 3, activation='relu', padding='same')(x)
x = layers.MaxPooling2D()(x)

x = layers.Conv2D(128, 3, activation='relu', padding='same')(x)
x = layers.MaxPooling2D()(x)

# 🧠 Simple attention
attention = layers.Conv2D(1, kernel_size=1, activation='sigmoid')(x)
x = layers.multiply([x, attention])

x = layers.Flatten()(x)
x = layers.Dense(128, activation='relu')(x)
x = layers.Dropout(0.5)(x)
outputs = layers.Dense(len(class_names), activation='softmax')(x)

model = models.Model(inputs, outputs)

# ====================
# Compile & train
# ====================
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20
)

# ====================
# Plot accuracy & loss
# ====================
plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='train_acc')
plt.plot(history.history['val_accuracy'], label='val_acc')
plt.title('Accuracy over epochs')
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='train_loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.title('Loss over epochs')
plt.legend()
plt.show()

import random
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image
import glob

# ✅ Pick random bajra image
all_image_paths = glob.glob('/content/bajra_sorted/**/*.*', recursive=True)
random_image_path = random.choice(all_image_paths)
print(f"Selected image: {random_image_path}")

# ✅ Preprocess
img = image.load_img(random_image_path, target_size=(img_height, img_width))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0) / 255.0

# ✅ Predict
predictions = model.predict(img_array)
predicted_class_idx = np.argmax(predictions[0])
predicted_class_name = class_names[predicted_class_idx]

print(f"🔍 Predicted class: {predicted_class_name}")
plt.imshow(image.load_img(random_image_path))
plt.title(f"Predicted: {predicted_class_name}")
plt.axis('off')
plt.show()

"""MobileNetV2"""

import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

# =====================
# Load bajra dataset
# =====================
data_dir = '/content/bajra_sorted'
batch_size = 32
img_height = 180
img_width = 180

train_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="training",
    seed=42,
    image_size=(img_height, img_width),
    batch_size=batch_size
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="validation",
    seed=42,
    image_size=(img_height, img_width),
    batch_size=batch_size
)

class_names = train_ds.class_names
print("Classes:", class_names)

AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

# =====================
# MobileNetV2 model
# =====================
base_model = tf.keras.applications.MobileNetV2(
    input_shape=(img_height, img_width, 3),
    include_top=False,
    weights='imagenet'
)
base_model.trainable = False  # freeze feature extractor

inputs = layers.Input(shape=(img_height, img_width, 3))
x = tf.keras.applications.mobilenet_v2.preprocess_input(inputs)
x = base_model(x, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dropout(0.3)(x)
outputs = layers.Dense(len(class_names), activation='softmax')(x)

model = models.Model(inputs, outputs)

# Compile
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# =====================
# Train for 20 epochs
# =====================
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20
)

# =====================
# Plot results
# =====================
plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='train_acc')
plt.plot(history.history['val_accuracy'], label='val_acc')
plt.title('Accuracy over epochs')
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='train_loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.title('Loss over epochs')
plt.legend()
plt.show()

import random
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image
import glob

all_image_paths = glob.glob('/content/bajra_sorted/**/*.*', recursive=True)
random_image_path = random.choice(all_image_paths)
print(f"Selected image: {random_image_path}")

img = image.load_img(random_image_path, target_size=(img_height, img_width))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array = tf.keras.applications.mobilenet_v2.preprocess_input(img_array)

predictions = model.predict(img_array)
predicted_class_idx = np.argmax(predictions[0])
predicted_class_name = class_names[predicted_class_idx]

print(f"🔍 Predicted class: {predicted_class_name}")
plt.imshow(image.load_img(random_image_path))
plt.title(f"Predicted: {predicted_class_name}")
plt.axis('off')
plt.show()

"""# accuracies"""

import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

# =====================
# Load bajra dataset
# =====================
data_dir = '/content/bajra_sorted'
batch_size = 16
img_height = 128
img_width = 128

train_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="training",
    seed=42,
    image_size=(img_height, img_width),
    batch_size=batch_size
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="validation",
    seed=42,
    image_size=(img_height, img_width),
    batch_size=batch_size
)

class_names = train_ds.class_names
AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

# =====================
# 1️⃣ Simple CNN
# =====================
model_cnn = models.Sequential([
    layers.Rescaling(1./255, input_shape=(img_height, img_width, 3)),
    layers.Conv2D(64, 3, activation='relu'),
    layers.MaxPooling2D(),
    layers.Conv2D(128, 3, activation='relu'),
    layers.MaxPooling2D(),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(len(class_names), activation='softmax')
])

model_cnn.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history_cnn = model_cnn.fit(train_ds, validation_data=val_ds, epochs=20)

# =====================
# 2️⃣ CNN + Attention
# =====================
inputs = layers.Input(shape=(img_height, img_width, 3))
x = layers.Rescaling(1./255)(inputs)
x = layers.Conv2D(64, 3, activation='relu', padding='same')(x)
x = layers.MaxPooling2D()(x)
x = layers.Conv2D(128, 3, activation='relu', padding='same')(x)
x = layers.MaxPooling2D()(x)
attention = layers.Conv2D(1, 1, activation='sigmoid')(x)
x = layers.multiply([x, attention])
x = layers.Flatten()(x)
x = layers.Dense(128, activation='relu')(x)
x = layers.Dropout(0.5)(x)
outputs = layers.Dense(len(class_names), activation='softmax')(x)
model_cnn_attention = models.Model(inputs, outputs)

model_cnn_attention.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history_cnn_attention = model_cnn_attention.fit(train_ds, validation_data=val_ds, epochs=20)

# =====================
# 3️⃣ MobileNetV2
# =====================
base_model = tf.keras.applications.MobileNetV2(
    input_shape=(img_height, img_width, 3),
    include_top=False,
    weights='imagenet'
)
base_model.trainable = False

inputs = layers.Input(shape=(img_height, img_width, 3))
x = tf.keras.applications.mobilenet_v2.preprocess_input(inputs)
x = base_model(x, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dropout(0.3)(x)
outputs = layers.Dense(len(class_names), activation='softmax')(x)

model_mobilenet = models.Model(inputs, outputs)
model_mobilenet.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history_mobilenet = model_mobilenet.fit(train_ds, validation_data=val_ds, epochs=20)

# =====================
# 📊 Compare accuracies
# =====================
plt.figure(figsize=(12,6))
plt.plot(history_cnn.history['val_accuracy'], label='CNN')
plt.plot(history_cnn_attention.history['val_accuracy'], label='CNN + Attention')
plt.plot(history_mobilenet.history['val_accuracy'], label='MobileNetV2')
plt.title('Validation Accuracy Comparison')
plt.xlabel('Epoch')
plt.ylabel('Validation Accuracy')
plt.legend()
plt.show()

import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt

# =====================
# Load ragi dataset
# =====================
data_dir = '/content/ragi'
batch_size = 16
img_height = 128
img_width = 128

train_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="training",
    seed=42,
    image_size=(img_height, img_width),
    batch_size=batch_size
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="validation",
    seed=42,
    image_size=(img_height, img_width),
    batch_size=batch_size
)

class_names = train_ds.class_names
AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

# =====================
# 1️⃣ Simple CNN
# =====================
model_cnn = models.Sequential([
    layers.Rescaling(1./255, input_shape=(img_height, img_width, 3)),
    layers.Conv2D(64, 3, activation='relu'),
    layers.MaxPooling2D(),
    layers.Conv2D(128, 3, activation='relu'),
    layers.MaxPooling2D(),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(len(class_names), activation='softmax')
])

model_cnn.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history_cnn = model_cnn.fit(train_ds, validation_data=val_ds, epochs=20)

# =====================
# 2️⃣ CNN + Attention
# =====================
inputs = layers.Input(shape=(img_height, img_width, 3))
x = layers.Rescaling(1./255)(inputs)
x = layers.Conv2D(64, 3, activation='relu', padding='same')(x)
x = layers.MaxPooling2D()(x)
x = layers.Conv2D(128, 3, activation='relu', padding='same')(x)
x = layers.MaxPooling2D()(x)
attention = layers.Conv2D(1, 1, activation='sigmoid')(x)
x = layers.multiply([x, attention])
x = layers.Flatten()(x)
x = layers.Dense(128, activation='relu')(x)
x = layers.Dropout(0.5)(x)
outputs = layers.Dense(len(class_names), activation='softmax')(x)
model_cnn_attention = models.Model(inputs, outputs)

model_cnn_attention.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history_cnn_attention = model_cnn_attention.fit(train_ds, validation_data=val_ds, epochs=20)

# =====================
# 3️⃣ MobileNetV2
# =====================
base_model = tf.keras.applications.MobileNetV2(
    input_shape=(img_height, img_width, 3),
    include_top=False,
    weights='imagenet'
)
base_model.trainable = False

inputs = layers.Input(shape=(img_height, img_width, 3))
x = tf.keras.applications.mobilenet_v2.preprocess_input(inputs)
x = base_model(x, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dropout(0.3)(x)
outputs = layers.Dense(len(class_names), activation='softmax')(x)

model_mobilenet = models.Model(inputs, outputs)
model_mobilenet.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history_mobilenet = model_mobilenet.fit(train_ds, validation_data=val_ds, epochs=20)

# =====================
# 📊 Compare accuracies
# =====================
plt.figure(figsize=(12,6))
plt.plot(history_cnn.history['val_accuracy'], label='CNN')
plt.plot(history_cnn_attention.history['val_accuracy'], label='CNN + Attention')
plt.plot(history_mobilenet.history['val_accuracy'], label='MobileNetV2')
plt.title('Validation Accuracy Comparison on Ragi')
plt.xlabel('Epoch')
plt.ylabel('Validation Accuracy')
plt.legend()
plt.show()

from google.colab import drive
drive.mount('/content/drive')